/** Config de Tailwind para el storefront público (9 páginas de site/*.html).
 *  Portada 1:1 desde la config inline que vivía en cada <head>, para que el CSS
 *  compilado (site/assets/css/app.css) sea idéntico al que generaba el CDN.
 *  El panel admin usa su propia config inline y NO entra aquí. */
module.exports = {
  darkMode: "class",
  content: [
    "./site/*.html",
    "./site/assets/js/*.js",
    "./site/assets/*.js",
  ],
  theme: {
    extend: {
      colors: {
        ink: "#0B0F1A",
        brand: "#1F5FD9",
        lime: "#8FD11F",
        paper: "#F7F8FA",
        "on-surface": "#001c3a",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#005322",
        "on-primary-fixed": "#001c39",
        error: "#ba1a1a",
        "surface-container-highest": "#d4e3ff",
        "primary-fixed-dim": "#a4c9ff",
        "tertiary-container": "#006d2f",
        "surface-variant": "#d4e3ff",
        "on-tertiary-fixed": "#002109",
        "on-tertiary-container": "#54f483",
        "tertiary-fixed-dim": "#3de273",
        tertiary: "#005222",
        "on-background": "#001c3a",
        "on-secondary": "#ffffff",
        "inverse-primary": "#a4c9ff",
        "on-secondary-fixed": "#001c38",
        "on-primary-container": "#c1d9ff",
        "surface-container": "#e6eeff",
        "on-surface-variant": "#424751",
        "on-primary-fixed-variant": "#004883",
        "error-container": "#ffdad6",
        "secondary-container": "#5da9fe",
        primary: "#004782",
        secondary: "#0060a8",
        "outline-variant": "#c2c6d2",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "primary-fixed": "#d4e3ff",
        "primary-container": "#185fa5",
        "inverse-surface": "#0c3158",
        "secondary-fixed-dim": "#a1c9ff",
        "tertiary-fixed": "#66ff8e",
        "surface-tint": "#1960a6",
        "surface-container-high": "#dde9ff",
        "secondary-fixed": "#d2e4ff",
        "inverse-on-surface": "#ebf1ff",
        surface: "#f9f9ff",
        "surface-container-low": "#eff3ff",
        "on-error-container": "#93000a",
        "surface-bright": "#f9f9ff",
        background: "#f9f9ff",
        "on-secondary-fixed-variant": "#004880",
        "on-secondary-container": "#003d6d",
        "surface-dim": "#c6dbff",
        outline: "#727782",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "section-padding": "80px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
        "stack-md": "16px",
      },
      fontFamily: {
        display: ["Barlow Condensed", "sans-serif"],
        body: ["Barlow", "sans-serif"],
        "headline-lg": ["Barlow Condensed", "sans-serif"],
        "body-md": ["Barlow", "sans-serif"],
        "headline-md": ["Barlow Condensed", "sans-serif"],
        "label-bold": ["Barlow", "sans-serif"],
        "body-sm": ["Barlow", "sans-serif"],
        "price-display": ["Barlow Condensed", "sans-serif"],
        "headline-xl": ["Barlow Condensed", "sans-serif"],
        "body-lg": ["Barlow", "sans-serif"],
        "headline-sm": ["Barlow Condensed", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-bold": ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "price-display": ["22px", { lineHeight: "1", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-sm": ["18px", { lineHeight: "1.2", fontWeight: "700" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
